comment out node install

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,10 +15,10 @@ NEWRELIC_VERSION=2.9.5.78
 S3_BUCKET=pradux-heroku-binaries
 
 # Node config 
-NODE_VERSION="0.4.7"
-NPM_VERSION="1.0.94"
-SCONS_VERSION="1.2.0"
-S3_BUCKET_NODE="heroku-buildpack-nodejs"
+# NODE_VERSION="0.4.7"
+# NPM_VERSION="1.0.94"
+# SCONS_VERSION="1.2.0"
+# S3_BUCKET_NODE="heroku-buildpack-nodejs"
 
 
 
@@ -78,8 +78,8 @@ BUNDLE_DIR="${CACHE_DIR}/bundles"
 LP_DIR=`cd $(dirname $0); cd ..; pwd`
 export COMPOSER_HOME="${CACHE_DIR}/.composer"
 
-CACHE_STORE_DIR=$CACHE_DIR"/node_modules/$NPM_VERSION"
-CACHE_TARGET_DIR=$BUILD_DIR"/node_modules"
+# CACHE_STORE_DIR=$CACHE_DIR"/node_modules/$NPM_VERSION"
+# CACHE_TARGET_DIR=$BUILD_DIR"/node_modules"
 
 # include .files when moving things around
 shopt -s dotglob
@@ -214,57 +214,57 @@ popd > /dev/null
 
 
 # s3 packages
-NODE_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/nodejs-${NODE_VERSION}.tgz"
-NPM_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/npm-${NPM_VERSION}.tgz"
-SCONS_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/scons-${SCONS_VERSION}.tgz"
+# NODE_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/nodejs-${NODE_VERSION}.tgz"
+# NPM_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/npm-${NPM_VERSION}.tgz"
+# SCONS_PACKAGE="http://${S3_BUCKET_NODE}.s3.amazonaws.com/scons-${SCONS_VERSION}.tgz"
 
 # vendor directories
-VENDORED_NODE="$(mktmpdir node)"
-VENDORED_NPM="$(mktmpdir npm)"
-VENDORED_SCONS="$(mktmpdir scons)"
+# VENDORED_NODE="$(mktmpdir node)"
+# VENDORED_NPM="$(mktmpdir npm)"
+# VENDORED_SCONS="$(mktmpdir scons)"
 
 # download and unpack packages
-echo "-----> Fetching Node.js binaries"
-mkdir -p $VENDORED_NODE  && curl $NODE_PACKAGE -s -o -  | tar xzf - -C $VENDORED_NODE
-mkdir -p $VENDORED_NPM   && curl $NPM_PACKAGE -s -o -   | tar xzf - -C $VENDORED_NPM
-mkdir -p $VENDORED_SCONS && curl $SCONS_PACKAGE -s -o - | tar xzf - -C $VENDORED_SCONS
+# echo "-----> Fetching Node.js binaries"
+# mkdir -p $VENDORED_NODE  && curl $NODE_PACKAGE -s -o -  | tar xzf - -C $VENDORED_NODE
+# mkdir -p $VENDORED_NPM   && curl $NPM_PACKAGE -s -o -   | tar xzf - -C $VENDORED_NPM
+# mkdir -p $VENDORED_SCONS && curl $SCONS_PACKAGE -s -o - | tar xzf - -C $VENDORED_SCONS
 
 
 # vendor node into the slug
-PATH="$BUILD_DIR/bin:$PATH"
-echo "-----> Vendoring node $NODE_VERSION"
-mkdir -p "$BUILD_DIR/bin"
-cp "$VENDORED_NODE/bin/node" "$BUILD_DIR/bin/node"
+# PATH="$BUILD_DIR/bin:$PATH"
+# echo "-----> Vendoring node $NODE_VERSION"
+# mkdir -p "$BUILD_DIR/bin"
+# cp "$VENDORED_NODE/bin/node" "$BUILD_DIR/bin/node"
 
 # setting up paths for building
-PATH="$VENDORED_SCONS:$VENDORED_NODE/bin:$PATH"
-INCLUDE_PATH="$VENDORED_NODE/include"
-export CPATH="$INCLUDE_PATH"
-export CPPPATH="$INCLUDE_PATH"
+# PATH="$VENDORED_SCONS:$VENDORED_NODE/bin:$PATH"
+# INCLUDE_PATH="$VENDORED_NODE/include"
+# export CPATH="$INCLUDE_PATH"
+# export CPPPATH="$INCLUDE_PATH"
 
-# unpack existing cache
-rm -rf $CACHE_TARGET_DIR
-if [ -d $CACHE_STORE_DIR ]; then
-  cp -a $CACHE_STORE_DIR $CACHE_TARGET_DIR
-fi
+# # unpack existing cache
+# rm -rf $CACHE_TARGET_DIR
+# if [ -d $CACHE_STORE_DIR ]; then
+#   cp -a $CACHE_STORE_DIR $CACHE_TARGET_DIR
+# fi
 
 # install dependencies with npm
-echo "-----> Installing dependencies with npm $NPM_VERSION"
-cd $BUILD_DIR
-HOME="$BUILD_DIR" GIT_DIR=".git" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js install 2>&1 | indent
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to install dependencies with npm"
-  exit 1
-else
-  echo "       Dependencies installed"
-fi
+# echo "-----> Installing dependencies with npm $NPM_VERSION"
+# cd $BUILD_DIR
+# HOME="$BUILD_DIR" GIT_DIR=".git" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js install 2>&1 | indent
+# if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+#   echo " !     Failed to install dependencies with npm"
+#   exit 1
+# else
+#   echo "       Dependencies installed"
+# fi
 
 # repack cache with new assets
-if [ -d $CACHE_TARGET_DIR ]; then
-  rm -rf $CACHE_STORE_DIR
-  mkdir -p $(dirname $CACHE_STORE_DIR)
-  cp -a $CACHE_TARGET_DIR $CACHE_STORE_DIR
-fi
+# if [ -d $CACHE_TARGET_DIR ]; then
+#   rm -rf $CACHE_STORE_DIR
+#   mkdir -p $(dirname $CACHE_STORE_DIR)
+#   cp -a $CACHE_TARGET_DIR $CACHE_STORE_DIR
+# fi
 
 
 
